### ISSUE TITLE
"Continues As" callout accessory should display route details for connecting route

### ISSUE THREAD

**Issue by frankus** [OneBusAway/onebusaway-iphone#412]
**Summary**: Tapping the callout accessory on a "Continues as" annotation brings up the route details for the route that terminates at the annotation. 

**Steps to Reproduce**:

1. Tap the "Show as Map" on a inbound RapidRide D.
2. Tap the red pin at W John and Queen Anne Ave W. 
3. Note the callout says "Continues as C - West Seattle". 
4. Tap the callout accessory button.

**Expected Behavior**: Display a route details view for the RapidRide C (the continuing route).

**Observed Behavior**: Displays a route details view for the RapidRide D (the terminating route).

This seems to happen with (at a minimum) all King County Metro routes that I've tried it on.

**Comment by aaronbrethorst** [comment]
Thanks for reporting this, @frankus. I don't suppose we could convince you to fix it, could we? :)

**Comment by frankus** [comment]
Working on it now…

**Comment by frankus** [comment]
Submitted PR #414 with a fix.

**Comment by aaronbrethorst** [comment]
Fixed by #414

**Comment by frankus** [comment]
Any idea when this might go live? It's still an issue on the App Store version.

**Comment by aaronbrethorst** [comment]
Soon. I've had a dozen other things on my plate, but am getting back to OBA with an eye on wrapping up the 2.4 release soon.
